spring:
  application:
    name: eurekaserver
server:
  port: 8761
eureka:
  instance:
    preferIpAddress: true
    hostname: eurekaserver
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://eurekaserver:8761/eureka
  server:
    waitTimeInMsWhenSyncEmpty: 5