spring:
  application:
    name: eureka-server
server:
  port: 8761
eureka:
  instance:
    preferIpAddress: true
    hostname: eureka-server
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka
  server:
    waitTimeInMsWhenSyncEmpty: 5